name = "rf-ranking-monitor-api"
main = "src/index.js"
compatibility_date = "2026-08-31"

[[d1_databases]]
binding = "DB"
database_name = "rf-ranking-monitor"
database_id = "5176d08d-25bc-4777-a9d0-b5fed50fd5a4"

[vars]
ALLOWED_ORIGIN = "https://chiaomao666.github.io"
